/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ywd-pc' at '17-12-7 下午4:32' with Gradle 3.1
 *
 * @author ywd-pc, @date 17-12-7 下午4:32
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
